pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t pbran/example-webserver:$DRONE_COMMIT_SHA .

  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run pbran/example-webserver:$DRONE_COMMIT_SHA /test.sh

  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u pbran -p $PASS
      - docker push pbran/example-webserver:$DRONE_COMMIT_SHA

  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull pbran/example-webserver:$DRONE_COMMIT_SHA
      - docker stack deploy -c ./docker-compose.yml example-webserver
      - docker service scale example-webserver_server=3
